"""update models

Revision ID: ea4e2ddd3b85
Revises: aee473ace2f1
Create Date: 2023-06-13 19:07:44.367446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4e2ddd3b85'
down_revision = 'aee473ace2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_media')
    op.add_column('shop_items', sa.Column('photo', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'photo')
    op.create_table('shop_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], name='shop_media_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shop_media_pkey')
    )
    # ### end Alembic commands ###
